homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 41.0214
  longitude: 28.9684
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Istanbul
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # ssl_certificate: /home/homeassistant/.homeassistant/certificate.pem
  # ssl_key: /home/homeassistant/.homeassistant/privkey.pem
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: ffmpeg
    input: !secret cam1_rtsp


#camera:
#  - platform: onvif
#    host: !secret cam1_host
#    port: !secret cam1_port
#    username: !secret cam1_user
#    password: !secret cam1_pass

mqtt:
  broker: !secret mqtt1_broker
  username: !secret mqtt1_user
  password: !secret mqtt1_pass

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
  - platform: nmap_tracker
    hosts: 192.168.1.0/24

zone:
  - name: Work
    latitude: !secret work_lat 
    longitude: !secret work_lon
    radius: 250
    icon: mdi:briefcase

  # This will override the default home zone
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_lon
    radius: 250
    icon: mdi:home-outline

# Example configuration.yaml entry
media_player:
  - platform: webostv
    host: !secret lg_webos
    timeout: 5
    filename: webostv.conf
    customize:
      sources:
        - livetv
        - youtube
        - netflix
        - HDMI4

light:
  - platform: yeelight
    devices:
      !secret ip_yeelight:
        name: Salon
        transition: 1000
        use_music_mode: True #(defaults to False)
        #save_on_change: False #(defaults to True)

sensor:
  - platform: etherscan
    address: !secret eth_asusk53s-main-1
    name: Ana Hesap-1
  - platform: etherscan
    address: !secret eth_asusk53s-main-2
    name: Ana Hesap-2
  - platform: etherscan
    address: !secret eth_beaglebone-main-1
    name: Beaglebone Hesap-1
  - platform: etherscan
    address: !secret eth_metamask-main-1
    name: Metamask Hesap-1
  - platform: coinmarketcap
    currency: Ethereum
    display_currency: USD
  - platform: alpha_vantage
    api_key: !secret apikey_alpha_vantage
    foreign_exchange:
    - name: USD_TRY
      from: USD
      to: TRY
  - platform: alpha_vantage
    api_key: !secret apikey_alpha_vantage
    foreign_exchange: 
    - name: EUR_TRY
      from: EUR
      to: TRY
  
  # Weather prediction
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness

  # Thx to https://community.home-assistant.io/t/using-the-lg-webos-source-value-to-trigger-events/4013/4
  - platform: template
    sensors:
      living_room_tv_source:
        value_template: '{{ states.media_player.lg_webos_smart_tv.attributes["source"] }}'
        friendly_name: 'LG TV Source'
